(*===============*)
(*  FindAlgebra  *)
(*===============*)

IncludeHeader@"CollectConstraints";
IncludeHeader@"NewUtils";
(*IncludeHeader@"ToHigherToSymmetrizedCanonical";*)

Options@FindAlgebra={Method->Solve,Constraints->{},Verify->False};
FindAlgebra[InputBulkBracket_,InputSchematicAnsatz_,OptionsPattern[]]~Y~Module[{
	CallStack,
	BulkBracket=InputBulkBracket,
	SchematicAnsatz=InputSchematicAnsatz,	
	BulkAnsatz,
	OutputBulkBracket,
	BoundaryAnsatz,
	BulkAnsatzParameters,
	BoundaryAnsatzParameters,
	ParameterSolution=0},

	If[!xAct`Hamilcar`Private`$CLI,
		CallStack=PrintTemporary@Dynamic@Refresh[
			GUICallStack@$CallStack,
			TrackedSymbols->{$CallStack}];
	];

	Block[{DetG},
		DetG[]:=1;
		BulkAnsatz=SchematicAnsatz;
		BulkAnsatz//=MakePermutedBulk;
		BulkAnsatz//=MakeSchematicBulk;
		BulkAnsatz//=MakeBulkAnsatz;
		OutputBulkBracket=BulkAnsatz;
		Print@OutputBulkBracket;
		BulkAnsatzParameters=BulkAnsatz;
		BulkAnsatzParameters//=ExtractParameters;
		BulkAnsatz//=TotalFrom;
		BoundaryAnsatz=BulkAnsatz;
		BoundaryAnsatz//=(#/.{RicciScalarCD->Zero})&;
		BoundaryAnsatz//=RecoverSchematicAnsatz;
		BoundaryAnsatz//=CurvatureReduction;
		BoundaryAnsatz//=MakeSchematicBoundaryCurrent;
		BoundaryAnsatz//=BoundaryCurrentToBoundary;
		Print@BoundaryAnsatz;
		BoundaryAnsatzParameters=BoundaryAnsatz;
		BoundaryAnsatzParameters//=ExtractParameters;
		BulkBracket//=TotalFrom;
		BulkBracket//=CleanInputBracket;
		ParameterSolution+=BulkBracket;
		ParameterSolution-=BulkAnsatz;
		ParameterSolution-=BoundaryAnsatz;
		ParameterSolution//=CollectTensors[#,CollectMethod->ToExpandedCanonical]&;
		(*Block[{RicciCD,RicciScalarCD},
			ParameterSolution//=(#/.{RicciCD->Zero,RicciScalarCD->Zero})&;
			ParameterSolution//=CollectTensors[#,
				CollectMethod->ToExpandedCanonical]&;
			ParameterSolution//=(#/.{RicciCD->Zero,RicciScalarCD->Zero})&;
			ParameterSolution//=CollectTensors[#,
				CollectMethod->ToExpandedCanonical]&;
		];*)
		ParameterSolution//=ObtainSolution[#,
			BulkAnsatzParameters,BoundaryAnsatzParameters,
			Method->OptionValue@Method]&;

		BulkBracket=InputBulkBracket;
		BulkBracket//=TotalFrom;
	];
	OutputBulkBracket//=(#/.ParameterSolution)&;
	OutputBulkBracket//=CollectTensors[#,CollectMethod->ToExpandedCanonical]&;
	BulkAnsatz//=(#/.ParameterSolution)&;
	BulkAnsatz//=CollectTensors[#,CollectMethod->ToExpandedCanonical]&;
	(*BracketAnsatz//=(#~CollectConstraints~ConstraintsList)&;*)
	If[OptionValue@Verify,
		BulkBracket~VerifyResult~BulkAnsatz;
	];

	If[!xAct`Hamilcar`Private`$CLI,
		FinishDynamic[];
		NotebookDelete@CallStack;
	];
OutputBulkBracket];
